version : "3.8"

services:
  app:
    image: employee_microservice
    build: 
      context: .
    ports: 
      - 5000:5000
    restart: on-failure:15
    depends_on:
      - server
  server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    logging:
      driver: none
    ports: 
      - 1433:1433
    volumes:
      - mssqlvolume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Kislay631

volumes:
  mssqlvolume:
